language: ruby

sudo: false

script: bundle exec rake travis

matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/Gemfile-ruby-1.8.7
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.0
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: gemfiles/Gemfile-edge
    - rvm: 2.2.0
      gemfile: Gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile-edge
    - rvm: jruby-18mode
      gemfile: gemfiles/Gemfile-ruby-1.8.7
    - rvm: jruby-19mode
      gemfile: Gemfile
    - rvm: jruby-head
      gemfile: Gemfile

  allow_failures:
    - rvm: jruby-head

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false
