language: ruby

sudo: false
dist: trusty

script: bundle exec rake travis

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile-edge

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
  include:
    - rvm: 2.0
      gemfile: gemfiles/Gemfile-2.0
    - rvm: 2.0
      gemfile: gemfiles/Gemfile-edge-2.0

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false
