language: ruby

gemfile:
  - Gemfile
  - Gemfile.1.8.7

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - jruby-head

script: bundle exec rake travis

matrix:
  include:
    - rvm: 2.1.0
      gemfile: Gemfile
      env: COVERAGE=true
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: Gemfile.1.8.7
    - rvm: 1.9.3
      gemfile: Gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: Gemfile.1.8.7
    - rvm: 2.1.0
      gemfile: Gemfile.1.8.7
    - rvm: jruby-18mode
      gemfile: Gemfile
    - rvm: jruby-19mode
      gemfile: Gemfile.1.8.7
    - rvm: jruby-head
      gemfile: Gemfile.1.8.7

  allow_failures:
    - rvm: jruby-head

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false

before_install:
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
